apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-push
spec:
  params:
    - name: repo-url
    - name: image-url
  workspaces:
    - name: source
    - name: dockerconfig  # 👈 Workspace for Docker credentials
  steps:
    - name: clone
      image: alpine/git
      script: |
        git clone $(params.repo-url) $(workspaces.source.path)

    - name: build-push
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=$(workspaces.source.path)/Dockerfile"
        - "--context=$(workspaces.source.path)"
        - "--destination=$(params.image-url)"
        - "--verbosity=debug"
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      volumeMounts:
        - name: dockerconfig
          mountPath: /kaniko/.docker
