apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: rails-ci-run
spec:
  pipelineRef:
    name: rails-ci-pipeline
  params:
    - name: repo-url
      value: https://github.com/gawalishankar/rails-k8s-gitops.git
    - name: image-url
      value: docker.io/shiv201/myapp:latest
  workspaces:
    - name: source
      volumeClaimTemplate:
        metadata:
          name: pipeline-workspace
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
    - name: dockerconfig
      secret:
        secretName: dockerhub-secret
