apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rails-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gawalishankar/rails-k8s-gitops.git
    targetRevision: HEAD
    path: .   # or path: manifests if you used a subfolder
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:    # <-- optional
      selfHeal: true
      prune: true
