apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  params:
    - name: repo-url
    - name: image-url
  tasks:
    - name: build
      taskRef:
        name: build-push
      params:
        - name: repo-url
          value: $(https://github.com/gawalishankar/rails-app.git)
        - name: image-url
          value: $(docker.io/shivdevops/myapp:latest)
