apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  params:
    - name: repo-url
    - name: image-url
  workspaces:
    - name: shared-data 
  tasks:
    - name: build
      taskRef:
        name: build-push
      params:
        - name: repo-url
          value:  https://github.com/gawalishankar/rails-k8s-gitops.git
        - name: image-url
          value: docker.io/shiv201/myapp:latest
      workspaces:
        - name: source          
          workspace: shared-data
