apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-push
spec:
  params:
    - name: repo-url
    - name: image-url
  workspaces:
    - name: source
  steps:
    - name: clone
      image: alpine/git
      script: |
        git clone (https://github.com/gawalishankar/rails-k8s-gitops.gitt) $(workspaces.source.path)

    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=$(workspaces.source.path)/Dockerfile"
        - "--context=$(workspaces.source.path)"
        - "--destination=(docker.io/shiv201/myapp:latest)"
