apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rails-ci-pipeline
spec:
  params:
    - name: repo-url
    - name: image-url

  tasks:
    - name: build
      taskRef:
        name: build-push
      params:
        - name: repo-url
          value:  https://github.com/gawalishankar/rails-k8s-gitops.git
        - name: image-url
          value: docker.io/shiv201/myapp:latest
